authors:
  consize-team:
    name: Consize Team
    description: Maintainers
    avatar: assets/logo-mark.png
  Ujunwa Njoku:
    name: Ujunwa Njoku
    description: Maintainer
    avatar: assets/logo-mark.png