apiVersion: v1
kind: Namespace
metadata:
  name: consize-demo
  labels:
    app.kubernetes.io/part-of: consize-local-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: consize-demo
  labels:
    app: checkout-api
    owner: platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
        owner: platform
    spec:
      containers:
        - name: checkout-api
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: consize-demo
  labels:
    app: checkout-api
spec:
  selector:
    app: checkout-api
  ports:
    - name: http
      port: 80
      targetPort: 80
